load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_library,
    name = "passes",
    srcs = [
        "__init__.py",
        "decompose_scaled_dot_product_attention.py",
        "normalize_clone_dim_order.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:pass_base",
        "//executorch/exir:dim_order_utils",
        "//executorch/exir/dialects:lib",
    ],
)
